### ISSUE TITLE
るびまHikiの再現環境の作り方をドキュメント化する

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/hiki#12]
「[今日からできる www.ruby-lang.org の手伝い方](http://magazine.rubyist.net/?0045-ForeWord#l1)」みたいなののるびまHiki版をドキュメント化する。

**Comment by miyohide** [comment]
現時点での動かし方を書いてみました。
https://github.com/rubima/rubima/wiki/DeploymentForNewBackend

とりあえず、ページを表示できたというレベルです。動作確認は取っていませんが、取り急ぎ。
